
export const GET_TRANSFORMERS = 'GET_TRANSFORMERS';
export const ADD_TRANSFORMER = 'ADD_TRANSFORMER';
export const EDIT_TRANSFORMER = 'EDIT_TRANSFORMER';
export const REMOVE_TRANSFORMER = 'REMOVE_TRANSFORMER';