
export const GET_TRANSFORMERS = 'GET_TRANSFORMERS';
export const ADD_TRANSFORMER = 'ADD_TRANSFORMER';
export const UPDATE_TRANSFORMER = 'UPDATE_TRANSFORMER';
export const REMOVE_TRANSFORMER = 'REMOVE_TRANSFORMER';
export const SEARCH_TRANSFORMER = 'SEARCH_TRANSFORMER';

export const SELECT_TRANSFORMER = 'SELECT_TRANSFORMER';